server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
#eureka:
 # client:
  #  serviceUrl:
    #  defaultZone: http://eureka-server-service:8761/eureka/

